### ISSUE TITLE
Oprava domácího úkolu

### ISSUE THREAD

**Issue by jakubledl** [EttTer/Hausaufgabe#1]
Ahoj!

Dobrá práce, úkol je skoro v pořádku, ale bohužel ho ještě nemůžu úplně uznat :-) Hlavní problém je, že komponenta `Task` nevrací správně utvořené HTML; když si to člověk přečte, je vidět, že `<div class="todo_tasks">` nemá uzavírací tag `</div>`. Druhý problém je, že tam ten `todo_tasks` vůbec je; podle zadání jednotlivé úkoly reprezentuje jen `<div class="task">`. `<div class="todo_tasks">` obsahuje celý seznam, což taky znamená, že `querySelector` na řádku 28 používá špatnou třídu.

Kdyby bylo něo nejasné, určitě se o tom můžeme pobavit v rámci téhle issue.

Jinak bych měl ještě pár poznámek, které nejsou chyby, ale spíš stylistické věci, ale ty kdyžtak napíšu potom :-)

**Comment by EttTer** [comment]
Ahoj Kubo,
moc díky za obsáhlou kontrolu. Opraveno, tím se vysvětlilo, že stylování nebylo tak, jak jsem předpokládala :) Moc děkuju za Tvůj čas. Mělo by to být teď už snad v pořádku. Měj krásný den

**Comment by jakubledl** [comment]
🥇
